package UI;

/**
 *
 * @author akifa
 */
public class BireyselKullaniciUI extends javax.swing.JFrame {

    private model.IndividualUser aktifKullanici;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BireyselKullaniciUI.class.getName());

    /**
     * Creates new form BireyselKullaniciUI
     */
    public BireyselKullaniciUI() {
        initComponents();
    }

    public BireyselKullaniciUI(model.IndividualUser user) {
        this.aktifKullanici = user; // Gelen kullanıcıyı içeri al
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        AdSoyadLabel = new javax.swing.JLabel();
        MusteriNoLabel = new javax.swing.JLabel();
        YonlendirmePanel = new javax.swing.JPanel();
        AnaSayfaBtn = new javax.swing.JButton();
        IslemlerBtn = new javax.swing.JButton();
        HesaplarBtn = new javax.swing.JButton();
        KartlarBtn = new javax.swing.JButton();
        FaturalarBtn = new javax.swing.JButton();
        VarliklarBtn = new javax.swing.JButton();
        GuncelKurBtn = new javax.swing.JButton();
        PanelContainer = new javax.swing.JPanel();
        AnaSayfaPanel = new javax.swing.JPanel();
        AnaSayfaVadesizHesapPanel = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        AnaSayfaKrediKartiPanel = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        IslemlerPanel = new javax.swing.JPanel();
        IslemlerPanelContainer = new javax.swing.JPanel();
        IslParaGönderPanel = new javax.swing.JPanel();
        GonderilecekAdTextF = new javax.swing.JTextField();
        GonderilecekSoyadTextF = new javax.swing.JTextField();
        GonderilecekIBANTextF = new javax.swing.JTextField();
        GonderilecekMiktarTextF = new javax.swing.JTextField();
        GonderBtn = new javax.swing.JButton();
        IslVadeliPanel = new javax.swing.JPanel();
        IslVadeSecenekleriComboBox = new javax.swing.JComboBox<>();
        IslVadeYatirilacakMiktarTextF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        IslDovizPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        IslBilgiPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IslParaGönderBtn = new javax.swing.JButton();
        IslVadeliBtn = new javax.swing.JButton();
        IslDovizBtn = new javax.swing.JButton();
        IslBilgiPanelBtn = new javax.swing.JButton();
        HesaplarPanel = new javax.swing.JPanel();
        HesaplarPanelContainer = new javax.swing.JPanel();
        HspVadesizPanel = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        HspVadeliPanel = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        HspDovizPanel = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        HspVadesizBtn = new javax.swing.JButton();
        HspVadeliBtn = new javax.swing.JButton();
        HspDövizBtn = new javax.swing.JButton();
        KartlarPanel = new javax.swing.JPanel();
        KrtBankaKartiPanel = new javax.swing.JPanel();
        lbl6 = new javax.swing.JLabel();
        KrtKrediKartiPanel = new javax.swing.JPanel();
        lbl7 = new javax.swing.JLabel();
        FaturalarPanel = new javax.swing.JPanel();
        FtrAboneliklerimBtn = new javax.swing.JButton();
        FtrFaturalarımBtn = new javax.swing.JButton();
        FaturalarPanelContainer = new javax.swing.JPanel();
        FtrAboneliklerimPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        FtrFaturalarımPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        VarliklarPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        GuncelKurPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UstPanel.setBackground(new java.awt.Color(0, 102, 255));

        AdSoyadLabel.setText("Ad Soyad");

        MusteriNoLabel.setText("MusteriNo");

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
                UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UstPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(AdSoyadLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MusteriNoLabel)
                                .addGap(22, 22, 22))
        );
        UstPanelLayout.setVerticalGroup(
                UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UstPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AdSoyadLabel)
                                        .addComponent(MusteriNoLabel))
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        AnaSayfaBtn.setText("jButton1");
        AnaSayfaBtn.addActionListener(this::AnaSayfaBtnActionPerformed);

        IslemlerBtn.setText("jButton2");
        IslemlerBtn.addActionListener(this::IslemlerBtnActionPerformed);

        HesaplarBtn.setText("jButton2");
        HesaplarBtn.addActionListener(this::HesaplarBtnActionPerformed);

        KartlarBtn.setText("jButton2");
        KartlarBtn.addActionListener(this::KartlarBtnActionPerformed);

        FaturalarBtn.setText("jButton2");
        FaturalarBtn.addActionListener(this::FaturalarBtnActionPerformed);

        VarliklarBtn.setText("jButton2");
        VarliklarBtn.addActionListener(this::VarliklarBtnActionPerformed);

        GuncelKurBtn.setText("jButton2");
        GuncelKurBtn.addActionListener(this::GuncelKurBtnActionPerformed);

        javax.swing.GroupLayout YonlendirmePanelLayout = new javax.swing.GroupLayout(YonlendirmePanel);
        YonlendirmePanel.setLayout(YonlendirmePanelLayout);
        YonlendirmePanelLayout.setHorizontalGroup(
                YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(YonlendirmePanelLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(AnaSayfaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IslemlerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HesaplarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KartlarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FaturalarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VarliklarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GuncelKurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        YonlendirmePanelLayout.setVerticalGroup(
                YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(YonlendirmePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AnaSayfaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IslemlerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HesaplarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KartlarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FaturalarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VarliklarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GuncelKurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelContainer.setLayout(new java.awt.CardLayout());

        lbl1.setText("Vadesiz Hesap");

        javax.swing.GroupLayout AnaSayfaVadesizHesapPanelLayout = new javax.swing.GroupLayout(AnaSayfaVadesizHesapPanel);
        AnaSayfaVadesizHesapPanel.setLayout(AnaSayfaVadesizHesapPanelLayout);
        AnaSayfaVadesizHesapPanelLayout.setHorizontalGroup(
                AnaSayfaVadesizHesapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaVadesizHesapPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl1)
                                .addContainerGap(629, Short.MAX_VALUE))
        );
        AnaSayfaVadesizHesapPanelLayout.setVerticalGroup(
                AnaSayfaVadesizHesapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaVadesizHesapPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl1)
                                .addContainerGap(198, Short.MAX_VALUE))
        );

        lbl2.setText("Kredi Kartı");

        javax.swing.GroupLayout AnaSayfaKrediKartiPanelLayout = new javax.swing.GroupLayout(AnaSayfaKrediKartiPanel);
        AnaSayfaKrediKartiPanel.setLayout(AnaSayfaKrediKartiPanelLayout);
        AnaSayfaKrediKartiPanelLayout.setHorizontalGroup(
                AnaSayfaKrediKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaKrediKartiPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AnaSayfaKrediKartiPanelLayout.setVerticalGroup(
                AnaSayfaKrediKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaKrediKartiPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl2)
                                .addContainerGap(198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AnaSayfaPanelLayout = new javax.swing.GroupLayout(AnaSayfaPanel);
        AnaSayfaPanel.setLayout(AnaSayfaPanelLayout);
        AnaSayfaPanelLayout.setHorizontalGroup(
                AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaPanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(AnaSayfaKrediKartiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AnaSayfaVadesizHesapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(122, Short.MAX_VALUE))
        );
        AnaSayfaPanelLayout.setVerticalGroup(
                AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AnaSayfaVadesizHesapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnaSayfaKrediKartiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelContainer.add(AnaSayfaPanel, "cardAnaSayfaPanel");

        IslemlerPanelContainer.setLayout(new java.awt.CardLayout());

        GonderilecekAdTextF.setText("jTextField1");

        GonderilecekSoyadTextF.setText("jTextField1");

        GonderilecekIBANTextF.setText("jTextField1");

        GonderilecekMiktarTextF.setText("jTextField1");

        GonderBtn.setText("Gönder");

        javax.swing.GroupLayout IslParaGönderPanelLayout = new javax.swing.GroupLayout(IslParaGönderPanel);
        IslParaGönderPanel.setLayout(IslParaGönderPanelLayout);
        IslParaGönderPanelLayout.setHorizontalGroup(
                IslParaGönderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslParaGönderPanelLayout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addGroup(IslParaGönderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(GonderilecekAdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GonderilecekSoyadTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GonderilecekIBANTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(IslParaGönderPanelLayout.createSequentialGroup()
                                                .addComponent(GonderilecekMiktarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(119, 119, 119)
                                                .addComponent(GonderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(9, Short.MAX_VALUE))
        );
        IslParaGönderPanelLayout.setVerticalGroup(
                IslParaGönderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslParaGönderPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(GonderilecekAdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(GonderilecekSoyadTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(GonderilecekIBANTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addGroup(IslParaGönderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(GonderilecekMiktarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GonderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        IslemlerPanelContainer.add(IslParaGönderPanel, "cardIslParaGönderPanel");

        IslVadeSecenekleriComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kısa (32 Gün) - %40 Faiz", "Orta (92 Gün) - %45 Faiz", "Uzun (181 Gün) - %48 Faiz", "Yıllık (365 Gün) - %50 Faiz" }));

        IslVadeYatirilacakMiktarTextF.setText("jTextField1");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jButton1.setText("jButton1");

        jLabel13.setText("jLabel13");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout IslVadeliPanelLayout = new javax.swing.GroupLayout(IslVadeliPanel);
        IslVadeliPanel.setLayout(IslVadeliPanelLayout);
        IslVadeliPanelLayout.setHorizontalGroup(
                IslVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(IslVadeYatirilacakMiktarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(115, 115, 115))
                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                .addGroup(IslVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(IslVadeSecenekleriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                                .addGap(256, 256, 256)
                                                .addComponent(jLabel11))
                                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(jLabel12)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(70, 70, 70))
        );
        IslVadeliPanelLayout.setVerticalGroup(
                IslVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(IslVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jButton2))
                                .addGap(131, 131, 131)
                                .addComponent(IslVadeSecenekleriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGroup(IslVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IslVadeliPanelLayout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(IslVadeYatirilacakMiktarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IslVadeliPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)
                                                .addGap(12, 12, 12)))
                                .addComponent(jLabel12)
                                .addContainerGap(43, Short.MAX_VALUE))
        );

        IslemlerPanelContainer.add(IslVadeliPanel, "cardIslVadeliPanel");

        jLabel8.setText("Dolar");

        jLabel9.setText("Euro");

        jLabel10.setText("Altın");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel14");

        jLabel16.setText("jLabel14");

        jLabel17.setText("jLabel14");

        jLabel18.setText("jLabel14");

        jLabel19.setText("jLabel14");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        jToggleButton3.setText("jToggleButton3");

        javax.swing.GroupLayout IslDovizPanelLayout = new javax.swing.GroupLayout(IslDovizPanel);
        IslDovizPanel.setLayout(IslDovizPanelLayout);
        IslDovizPanelLayout.setHorizontalGroup(
                IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                                .addGap(148, 148, 148)
                                                .addComponent(jLabel9))
                                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addComponent(jLabel19))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IslDovizPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IslDovizPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(121, 121, 121))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IslDovizPanelLayout.createSequentialGroup()
                                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel18))
                                                .addGap(112, 112, 112))))
                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95))
                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jToggleButton1)
                                .addGap(61, 61, 61)
                                .addComponent(jToggleButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jToggleButton3)
                                .addGap(74, 74, 74))
        );
        IslDovizPanelLayout.setVerticalGroup(
                IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslDovizPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jToggleButton1)
                                        .addComponent(jToggleButton2)
                                        .addComponent(jToggleButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(IslDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel18))
                                .addGap(43, 43, 43))
        );

        IslemlerPanelContainer.add(IslDovizPanel, "cardIslDovizPanel");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout IslBilgiPanelLayout = new javax.swing.GroupLayout(IslBilgiPanel);
        IslBilgiPanel.setLayout(IslBilgiPanelLayout);
        IslBilgiPanelLayout.setHorizontalGroup(
                IslBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslBilgiPanelLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jLabel1)
                                .addContainerGap(238, Short.MAX_VALUE))
        );
        IslBilgiPanelLayout.setVerticalGroup(
                IslBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IslBilgiPanelLayout.createSequentialGroup()
                                .addContainerGap(185, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(235, 235, 235))
        );

        IslemlerPanelContainer.add(IslBilgiPanel, "cardIslBilgiPanel");

        IslParaGönderBtn.setText("Para Gönderme");
        IslParaGönderBtn.addActionListener(this::IslParaGönderBtnActionPerformed);

        IslVadeliBtn.setText("Vadeli Hesap İşlemleri");
        IslVadeliBtn.addActionListener(this::IslVadeliBtnActionPerformed);

        IslDovizBtn.setText("Döviz İşlemleri");
        IslDovizBtn.addActionListener(this::IslDovizBtnActionPerformed);

        IslBilgiPanelBtn.setText("BilgiPaneli");
        IslBilgiPanelBtn.addActionListener(this::IslBilgiPanelBtnActionPerformed);

        javax.swing.GroupLayout IslemlerPanelLayout = new javax.swing.GroupLayout(IslemlerPanel);
        IslemlerPanel.setLayout(IslemlerPanelLayout);
        IslemlerPanelLayout.setHorizontalGroup(
                IslemlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslemlerPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(IslemlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IslDovizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IslParaGönderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IslVadeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IslBilgiPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addComponent(IslemlerPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(81, Short.MAX_VALUE))
        );
        IslemlerPanelLayout.setVerticalGroup(
                IslemlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IslemlerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(IslemlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IslemlerPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(IslemlerPanelLayout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(IslBilgiPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(IslParaGönderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(IslVadeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(IslDovizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelContainer.add(IslemlerPanel, "cardIslemlerPanel");

        HesaplarPanelContainer.setLayout(new java.awt.CardLayout());

        lbl3.setText("vadesiz");

        javax.swing.GroupLayout HspVadesizPanelLayout = new javax.swing.GroupLayout(HspVadesizPanel);
        HspVadesizPanel.setLayout(HspVadesizPanelLayout);
        HspVadesizPanelLayout.setHorizontalGroup(
                HspVadesizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspVadesizPanelLayout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(lbl3)
                                .addContainerGap(349, Short.MAX_VALUE))
        );
        HspVadesizPanelLayout.setVerticalGroup(
                HspVadesizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspVadesizPanelLayout.createSequentialGroup()
                                .addComponent(lbl3)
                                .addGap(0, 406, Short.MAX_VALUE))
        );

        HesaplarPanelContainer.add(HspVadesizPanel, "cardHspVadesizPanel");

        lbl4.setText("vadeli");

        javax.swing.GroupLayout HspVadeliPanelLayout = new javax.swing.GroupLayout(HspVadeliPanel);
        HspVadeliPanel.setLayout(HspVadeliPanelLayout);
        HspVadeliPanelLayout.setHorizontalGroup(
                HspVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspVadeliPanelLayout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(lbl4)
                                .addContainerGap(389, Short.MAX_VALUE))
        );
        HspVadeliPanelLayout.setVerticalGroup(
                HspVadeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspVadeliPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl4)
                                .addContainerGap(400, Short.MAX_VALUE))
        );

        HesaplarPanelContainer.add(HspVadeliPanel, "cardHspVadeliPanel");

        lbl5.setText("döviz");

        javax.swing.GroupLayout HspDovizPanelLayout = new javax.swing.GroupLayout(HspDovizPanel);
        HspDovizPanel.setLayout(HspDovizPanelLayout);
        HspDovizPanelLayout.setHorizontalGroup(
                HspDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspDovizPanelLayout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(lbl5)
                                .addContainerGap(385, Short.MAX_VALUE))
        );
        HspDovizPanelLayout.setVerticalGroup(
                HspDovizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HspDovizPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl5)
                                .addContainerGap(400, Short.MAX_VALUE))
        );

        HesaplarPanelContainer.add(HspDovizPanel, "cardHspDovizPanel");

        HspVadesizBtn.setText("Vadesiz");
        HspVadesizBtn.addActionListener(this::HspVadesizBtnActionPerformed);

        HspVadeliBtn.setText("Vadeli");
        HspVadeliBtn.addActionListener(this::HspVadeliBtnActionPerformed);

        HspDövizBtn.setText("Döviz");
        HspDövizBtn.addActionListener(this::HspDövizBtnActionPerformed);

        javax.swing.GroupLayout HesaplarPanelLayout = new javax.swing.GroupLayout(HesaplarPanel);
        HesaplarPanel.setLayout(HesaplarPanelLayout);
        HesaplarPanelLayout.setHorizontalGroup(
                HesaplarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HesaplarPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(HesaplarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HspVadesizBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HspVadeliBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HspDövizBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HesaplarPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        HesaplarPanelLayout.setVerticalGroup(
                HesaplarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HesaplarPanelLayout.createSequentialGroup()
                                .addGroup(HesaplarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(HesaplarPanelLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(HspVadesizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(HspVadeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(HspDövizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(HesaplarPanelLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(HesaplarPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelContainer.add(HesaplarPanel, "cardHesaplarPanel");

        lbl6.setText("Banka Kartı");

        javax.swing.GroupLayout KrtBankaKartiPanelLayout = new javax.swing.GroupLayout(KrtBankaKartiPanel);
        KrtBankaKartiPanel.setLayout(KrtBankaKartiPanelLayout);
        KrtBankaKartiPanelLayout.setHorizontalGroup(
                KrtBankaKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KrtBankaKartiPanelLayout.createSequentialGroup()
                                .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 589, Short.MAX_VALUE))
        );
        KrtBankaKartiPanelLayout.setVerticalGroup(
                KrtBankaKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KrtBankaKartiPanelLayout.createSequentialGroup()
                                .addComponent(lbl6)
                                .addGap(0, 186, Short.MAX_VALUE))
        );

        lbl7.setText("Kredi Kartı");

        javax.swing.GroupLayout KrtKrediKartiPanelLayout = new javax.swing.GroupLayout(KrtKrediKartiPanel);
        KrtKrediKartiPanel.setLayout(KrtKrediKartiPanelLayout);
        KrtKrediKartiPanelLayout.setHorizontalGroup(
                KrtKrediKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KrtKrediKartiPanelLayout.createSequentialGroup()
                                .addComponent(lbl7)
                                .addGap(0, 627, Short.MAX_VALUE))
        );
        KrtKrediKartiPanelLayout.setVerticalGroup(
                KrtKrediKartiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KrtKrediKartiPanelLayout.createSequentialGroup()
                                .addComponent(lbl7)
                                .addGap(0, 198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KartlarPanelLayout = new javax.swing.GroupLayout(KartlarPanel);
        KartlarPanel.setLayout(KartlarPanelLayout);
        KartlarPanelLayout.setHorizontalGroup(
                KartlarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KartlarPanelLayout.createSequentialGroup()
                                .addGroup(KartlarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(KartlarPanelLayout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(KrtBankaKartiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(KartlarPanelLayout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(KrtKrediKartiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(160, Short.MAX_VALUE))
        );
        KartlarPanelLayout.setVerticalGroup(
                KartlarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KartlarPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(KrtBankaKartiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KrtKrediKartiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelContainer.add(KartlarPanel, "cardKartlarPanel");

        FtrAboneliklerimBtn.setText("Aboneliklerim");
        FtrAboneliklerimBtn.addActionListener(this::FtrAboneliklerimBtnActionPerformed);

        FtrFaturalarımBtn.setText("Faturalarım");
        FtrFaturalarımBtn.addActionListener(this::FtrFaturalarımBtnActionPerformed);

        FaturalarPanelContainer.setLayout(new java.awt.CardLayout());

        jLabel31.setText("abn");

        javax.swing.GroupLayout FtrAboneliklerimPanelLayout = new javax.swing.GroupLayout(FtrAboneliklerimPanel);
        FtrAboneliklerimPanel.setLayout(FtrAboneliklerimPanelLayout);
        FtrAboneliklerimPanelLayout.setHorizontalGroup(
                FtrAboneliklerimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FtrAboneliklerimPanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel31)
                                .addContainerGap(557, Short.MAX_VALUE))
        );
        FtrAboneliklerimPanelLayout.setVerticalGroup(
                FtrAboneliklerimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FtrAboneliklerimPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel31)
                                .addContainerGap(319, Short.MAX_VALUE))
        );

        FaturalarPanelContainer.add(FtrAboneliklerimPanel, "cardFtrAboneliklerimPanel");

        jLabel32.setText("ftr");

        javax.swing.GroupLayout FtrFaturalarımPanelLayout = new javax.swing.GroupLayout(FtrFaturalarımPanel);
        FtrFaturalarımPanel.setLayout(FtrFaturalarımPanelLayout);
        FtrFaturalarımPanelLayout.setHorizontalGroup(
                FtrFaturalarımPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FtrFaturalarımPanelLayout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel32)
                                .addContainerGap(434, Short.MAX_VALUE))
        );
        FtrFaturalarımPanelLayout.setVerticalGroup(
                FtrFaturalarımPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FtrFaturalarımPanelLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel32)
                                .addContainerGap(244, Short.MAX_VALUE))
        );

        FaturalarPanelContainer.add(FtrFaturalarımPanel, "cardFtrFaturalarımPanel");

        javax.swing.GroupLayout FaturalarPanelLayout = new javax.swing.GroupLayout(FaturalarPanel);
        FaturalarPanel.setLayout(FaturalarPanelLayout);
        FaturalarPanelLayout.setHorizontalGroup(
                FaturalarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FaturalarPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(FaturalarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FtrFaturalarımBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FtrAboneliklerimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(FaturalarPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );
        FaturalarPanelLayout.setVerticalGroup(
                FaturalarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FaturalarPanelLayout.createSequentialGroup()
                                .addGroup(FaturalarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(FaturalarPanelLayout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(FtrAboneliklerimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(FtrFaturalarımBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FaturalarPanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(FaturalarPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        PanelContainer.add(FaturalarPanel, "cardFaturalarPanel");

        jLabel20.setText("jLabel20");

        jLabel21.setText("jLabel21");

        jLabel22.setText("jLabel22");

        jLabel23.setText("jLabel23");

        javax.swing.GroupLayout VarliklarPanelLayout = new javax.swing.GroupLayout(VarliklarPanel);
        VarliklarPanel.setLayout(VarliklarPanelLayout);
        VarliklarPanelLayout.setHorizontalGroup(
                VarliklarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VarliklarPanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel20)
                                .addGap(196, 196, 196)
                                .addComponent(jLabel21)
                                .addGap(184, 184, 184)
                                .addComponent(jLabel22)
                                .addGap(165, 165, 165)
                                .addComponent(jLabel23)
                                .addContainerGap(189, Short.MAX_VALUE))
        );
        VarliklarPanelLayout.setVerticalGroup(
                VarliklarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VarliklarPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(VarliklarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23))
                                .addContainerGap(366, Short.MAX_VALUE))
        );

        PanelContainer.add(VarliklarPanel, "cardVarliklarPanel");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        javax.swing.GroupLayout GuncelKurPanelLayout = new javax.swing.GroupLayout(GuncelKurPanel);
        GuncelKurPanel.setLayout(GuncelKurPanelLayout);
        GuncelKurPanelLayout.setHorizontalGroup(
                GuncelKurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GuncelKurPanelLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel24)
                                .addGap(225, 225, 225)
                                .addComponent(jLabel25)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel26)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel27)
                                .addContainerGap(147, Short.MAX_VALUE))
        );
        GuncelKurPanelLayout.setVerticalGroup(
                GuncelKurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GuncelKurPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(GuncelKurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27))
                                .addContainerGap(344, Short.MAX_VALUE))
        );

        PanelContainer.add(GuncelKurPanel, "cardGuncelKurPanel");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(YonlendirmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YonlendirmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void AnaSayfaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardAnaSayfaPanel");
    }

    private void IslemlerBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardIslemlerPanel");

    }

    private void HesaplarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardHesaplarPanel");
    }

    private void KartlarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardKartlarPanel");
    }

    private void FaturalarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardFaturalarPanel");
    }

    private void VarliklarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardVarliklarPanel");
    }

    private void GuncelKurBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardGuncelKurPanel");
    }

    private void IslBilgiPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        islemlerSayfaDegistir("cardIslBilgiPanel");
    }

    private void IslParaGönderBtnActionPerformed(java.awt.event.ActionEvent evt) {
        islemlerSayfaDegistir("cardIslParaGönderPanel");
    }

    private void IslVadeliBtnActionPerformed(java.awt.event.ActionEvent evt) {
        islemlerSayfaDegistir("cardIslVadeliPanel");
    }

    private void IslDovizBtnActionPerformed(java.awt.event.ActionEvent evt) {
        islemlerSayfaDegistir("cardIslDovizPanel");
    }

    private void HspVadesizBtnActionPerformed(java.awt.event.ActionEvent evt) {
        hesaplarSayfaDegistir("cardHspVadesizPanel");
    }

    private void HspVadeliBtnActionPerformed(java.awt.event.ActionEvent evt) {
        hesaplarSayfaDegistir("cardHspVadeliPanel");
    }

    private void HspDövizBtnActionPerformed(java.awt.event.ActionEvent evt) {
        hesaplarSayfaDegistir("cardHspDovizPanel");
    }

    private void FtrAboneliklerimBtnActionPerformed(java.awt.event.ActionEvent evt) {
        faturalarSayfaDegistir("cardFtrAboneliklerimPanel");
    }

    private void FtrFaturalarımBtnActionPerformed(java.awt.event.ActionEvent evt) {
        faturalarSayfaDegistir("cardFtrFaturalarımPanel");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BireyselKullaniciUI().setVisible(true));
    }


    //=======Kendi özel fonksiyonlarım=========
    private void mainSayfaDegistir(String kartIsmi) {
        // 1. Kartı Değiştir
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContainer.getLayout();
        layout.show(PanelContainer, kartIsmi);
    }

    private void islemlerSayfaDegistir(String kartIsmi){
        java.awt.CardLayout subCardLayout = (java.awt.CardLayout) IslemlerPanelContainer.getLayout();
        subCardLayout.show(IslemlerPanelContainer, kartIsmi);
    }

    private void hesaplarSayfaDegistir(String kartIsmi){
        java.awt.CardLayout subCardLayout = (java.awt.CardLayout) HesaplarPanelContainer.getLayout();
        subCardLayout.show(HesaplarPanelContainer, kartIsmi);
    }

    private void faturalarSayfaDegistir(String kartIsmi){
        java.awt.CardLayout subCardLayout = (java.awt.CardLayout) FaturalarPanelContainer.getLayout();
        subCardLayout.show(FaturalarPanelContainer, kartIsmi);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel AdSoyadLabel;
    private javax.swing.JButton AnaSayfaBtn;
    private javax.swing.JPanel AnaSayfaKrediKartiPanel;
    private javax.swing.JPanel AnaSayfaPanel;
    private javax.swing.JPanel AnaSayfaVadesizHesapPanel;
    private javax.swing.JButton FaturalarBtn;
    private javax.swing.JPanel FaturalarPanel;
    private javax.swing.JPanel FaturalarPanelContainer;
    private javax.swing.JButton FtrAboneliklerimBtn;
    private javax.swing.JPanel FtrAboneliklerimPanel;
    private javax.swing.JButton FtrFaturalarımBtn;
    private javax.swing.JPanel FtrFaturalarımPanel;
    private javax.swing.JButton GonderBtn;
    private javax.swing.JTextField GonderilecekAdTextF;
    private javax.swing.JTextField GonderilecekIBANTextF;
    private javax.swing.JTextField GonderilecekMiktarTextF;
    private javax.swing.JTextField GonderilecekSoyadTextF;
    private javax.swing.JButton GuncelKurBtn;
    private javax.swing.JPanel GuncelKurPanel;
    private javax.swing.JButton HesaplarBtn;
    private javax.swing.JPanel HesaplarPanel;
    private javax.swing.JPanel HesaplarPanelContainer;
    private javax.swing.JPanel HspDovizPanel;
    private javax.swing.JButton HspDövizBtn;
    private javax.swing.JButton HspVadeliBtn;
    private javax.swing.JPanel HspVadeliPanel;
    private javax.swing.JButton HspVadesizBtn;
    private javax.swing.JPanel HspVadesizPanel;
    private javax.swing.JPanel IslBilgiPanel;
    private javax.swing.JButton IslBilgiPanelBtn;
    private javax.swing.JButton IslDovizBtn;
    private javax.swing.JPanel IslDovizPanel;
    private javax.swing.JButton IslParaGönderBtn;
    private javax.swing.JPanel IslParaGönderPanel;
    private javax.swing.JComboBox<String> IslVadeSecenekleriComboBox;
    private javax.swing.JTextField IslVadeYatirilacakMiktarTextF;
    private javax.swing.JButton IslVadeliBtn;
    private javax.swing.JPanel IslVadeliPanel;
    private javax.swing.JButton IslemlerBtn;
    private javax.swing.JPanel IslemlerPanel;
    private javax.swing.JPanel IslemlerPanelContainer;
    private javax.swing.JButton KartlarBtn;
    private javax.swing.JPanel KartlarPanel;
    private javax.swing.JPanel KrtBankaKartiPanel;
    private javax.swing.JPanel KrtKrediKartiPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MusteriNoLabel;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JPanel UstPanel;
    private javax.swing.JButton VarliklarBtn;
    private javax.swing.JPanel VarliklarPanel;
    private javax.swing.JPanel YonlendirmePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    // End of variables declaration
}

