package UI;

public class KurumsalKullaniciUI extends javax.swing.JFrame {

    private model.EnterpriseUser aktifSirket;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KurumsalKullaniciUI.class.getName());

    /**
     * Creates new form KurumsalKullaniciUI
     */
    public KurumsalKullaniciUI() {
        initComponents();
    }

    public KurumsalKullaniciUI(model.EnterpriseUser user) {
        this.aktifSirket = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        MainPanel = new javax.swing.JPanel();
        YonlendirmePanel = new javax.swing.JPanel();
        AnaSayfaBtn = new javax.swing.JButton();
        AboneYonetimiBtn = new javax.swing.JButton();
        FaturaYonetimiBtn = new javax.swing.JButton();
        PanelContainer = new javax.swing.JPanel();
        AnaSayfaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AboneYonetimiPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        FaturaYonetimiPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnaSayfaBtn.setText("jButton1");
        AnaSayfaBtn.addActionListener(this::AnaSayfaBtnActionPerformed);

        AboneYonetimiBtn.setText("jButton2");
        AboneYonetimiBtn.addActionListener(this::AboneYonetimiBtnActionPerformed);

        FaturaYonetimiBtn.setText("jButton2");
        FaturaYonetimiBtn.addActionListener(this::FaturaYonetimiBtnActionPerformed);

        javax.swing.GroupLayout YonlendirmePanelLayout = new javax.swing.GroupLayout(YonlendirmePanel);
        YonlendirmePanel.setLayout(YonlendirmePanelLayout);
        YonlendirmePanelLayout.setHorizontalGroup(
                YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YonlendirmePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AnaSayfaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AboneYonetimiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FaturaYonetimiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(404, 404, 404))
        );
        YonlendirmePanelLayout.setVerticalGroup(
                YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(YonlendirmePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(YonlendirmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AnaSayfaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AboneYonetimiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FaturaYonetimiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setText("mevcutbakiye");

        jLabel4.setText("beklenentahsilat");

        jLabel5.setText("abonesayısı");

        javax.swing.GroupLayout AnaSayfaPanelLayout = new javax.swing.GroupLayout(AnaSayfaPanel);
        AnaSayfaPanel.setLayout(AnaSayfaPanelLayout);
        AnaSayfaPanelLayout.setHorizontalGroup(
                AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addContainerGap(836, Short.MAX_VALUE))
        );
        AnaSayfaPanelLayout.setVerticalGroup(
                AnaSayfaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnaSayfaPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5)
                                .addContainerGap(233, Short.MAX_VALUE))
        );

        PanelContainer.add(AnaSayfaPanel, "cardAnaSayfaPanel");

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("yeniabonekayıt");

        javax.swing.GroupLayout AboneYonetimiPanelLayout = new javax.swing.GroupLayout(AboneYonetimiPanel);
        AboneYonetimiPanel.setLayout(AboneYonetimiPanelLayout);
        AboneYonetimiPanelLayout.setHorizontalGroup(
                AboneYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboneYonetimiPanelLayout.createSequentialGroup()
                                .addGroup(AboneYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AboneYonetimiPanelLayout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel2)
                                                .addGap(48, 48, 48)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(AboneYonetimiPanelLayout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(77, Short.MAX_VALUE))
        );
        AboneYonetimiPanelLayout.setVerticalGroup(
                AboneYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboneYonetimiPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboneYonetimiPanelLayout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(14, 14, 14))
        );

        PanelContainer.add(AboneYonetimiPanel, "cardAboneYonetimiPanel");

        jLabel3.setText("jLabel3");

        jButton2.setText("faturaoluşturma");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout FaturaYonetimiPanelLayout = new javax.swing.GroupLayout(FaturaYonetimiPanel);
        FaturaYonetimiPanel.setLayout(FaturaYonetimiPanelLayout);
        FaturaYonetimiPanelLayout.setHorizontalGroup(
                FaturaYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FaturaYonetimiPanelLayout.createSequentialGroup()
                                .addGroup(FaturaYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(FaturaYonetimiPanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel3))
                                        .addGroup(FaturaYonetimiPanelLayout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jButton2)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(62, Short.MAX_VALUE))
        );
        FaturaYonetimiPanelLayout.setVerticalGroup(
                FaturaYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FaturaYonetimiPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(32, 32, 32))
                        .addGroup(FaturaYonetimiPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        PanelContainer.add(FaturaYonetimiPanel, "cardFaturaYonetimiPanel");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(YonlendirmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(YonlendirmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void AnaSayfaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardAnaSayfaPanel");
    }

    private void AboneYonetimiBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardAboneYonetimiPanel");
    }

    private void FaturaYonetimiBtnActionPerformed(java.awt.event.ActionEvent evt) {
        mainSayfaDegistir("cardFaturaYonetimiPanel");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KurumsalKullaniciUI().setVisible(true));
    }

    //=======Kendi özel fonksiyonlarım=========
    private void mainSayfaDegistir(String kartIsmi) {
        // 1. Kartı Değiştir
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContainer.getLayout();
        layout.show(PanelContainer, kartIsmi);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton AboneYonetimiBtn;
    private javax.swing.JPanel AboneYonetimiPanel;
    private javax.swing.JButton AnaSayfaBtn;
    private javax.swing.JPanel AnaSayfaPanel;
    private javax.swing.JButton FaturaYonetimiBtn;
    private javax.swing.JPanel FaturaYonetimiPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JPanel YonlendirmePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration
}

