package UI;

import UI.BireyselKullaniciUI;
import Managers.DataBaseManager;
import model.IndividualUser;


public class MainMenuUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuUI.class.getName());

    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI() {
        initComponents();
        GeriDonBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        AnaMenuKullaniciTipiRDB = new javax.swing.ButtonGroup();
        BireyselGirisTipiRDB = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        MainPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        BankaAdiLabel = new javax.swing.JLabel();
        AdminControlsBtn = new javax.swing.JButton();
        TarihveSaatLabel = new javax.swing.JLabel();
        PanelContainer = new javax.swing.JPanel();
        FirstPanel = new javax.swing.JPanel();
        BireyselRadioBtn = new javax.swing.JRadioButton();
        KurumsalRadioBtn = new javax.swing.JRadioButton();
        GirisYapBtn = new javax.swing.JButton();
        HesapOlusturBtn = new javax.swing.JButton();
        BireyselGirisYapPanel = new javax.swing.JPanel();
        BireyselGirisTamamlaBtn = new javax.swing.JButton();
        TCGirisRadioBtn = new javax.swing.JRadioButton();
        MusteriNoGirisRadioBtn = new javax.swing.JRadioButton();
        TelNoGirisRadioBtn = new javax.swing.JRadioButton();
        BireyselTypeGirisTextF = new javax.swing.JTextField();
        BireyselSifreGirisPasswordTF = new javax.swing.JPasswordField();
        BireyselGirisSifreGoster = new javax.swing.JCheckBox();
        KurumsalGirisPanel = new javax.swing.JPanel();
        KurumsalGirisTamamlaBtn = new javax.swing.JButton();
        KurumKoduGirisTextF = new javax.swing.JTextField();
        KurumsalSifreGirisPasswordTF = new javax.swing.JPasswordField();
        KurumsalGirisSifreGoster = new javax.swing.JCheckBox();
        BireyselKayitPanel = new javax.swing.JPanel();
        BireyselKayıtTamamlaBtn = new javax.swing.JButton();
        BireyselAdGirisTextF = new javax.swing.JTextField();
        BireyselSoyadGirisTextF = new javax.swing.JTextField();
        BireyselTcGirisFormattedTextF = new javax.swing.JFormattedTextField();
        BireyselDogumTGirisFormattedTextF = new javax.swing.JFormattedTextField();
        BireyselSehirGirisTextF = new javax.swing.JTextField();
        BireyselTelefonGirisTextF = new javax.swing.JFormattedTextField();
        BireyselSifreKayitPasswordTF = new javax.swing.JPasswordField();
        BireyselKayitSifreGoster = new javax.swing.JCheckBox();
        KurumsalKayitPanel = new javax.swing.JPanel();
        KurumsalKayıtTamamlaBtn = new javax.swing.JButton();
        KurumsalAdGirisTextF = new javax.swing.JTextField();
        KurumsalTarihGirisFormattedTF = new javax.swing.JFormattedTextField();
        KurumsalSehirGirisTextF = new javax.swing.JTextField();
        KurumsalSifreKayitPasswordTF = new javax.swing.JPasswordField();
        KurumsalKayitSifreGoster = new javax.swing.JCheckBox();
        GeriDonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UstPanel.setBackground(new java.awt.Color(0, 102, 153));

        BankaAdiLabel.setText("DİNO BANK");

        AdminControlsBtn.setText("AdminControls");

        TarihveSaatLabel.setText("Tarih ve Saat");

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
                UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UstPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(TarihveSaatLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                                .addComponent(BankaAdiLabel)
                                .addGap(333, 333, 333)
                                .addComponent(AdminControlsBtn)
                                .addGap(16, 16, 16))
        );
        UstPanelLayout.setVerticalGroup(
                UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UstPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BankaAdiLabel)
                                        .addComponent(AdminControlsBtn)
                                        .addComponent(TarihveSaatLabel))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelContainer.setMinimumSize(new java.awt.Dimension(600, 350));
        PanelContainer.setPreferredSize(new java.awt.Dimension(600, 350));
        PanelContainer.setLayout(new java.awt.CardLayout());

        AnaMenuKullaniciTipiRDB.add(BireyselRadioBtn);
        BireyselRadioBtn.setText("Bireysel");

        AnaMenuKullaniciTipiRDB.add(KurumsalRadioBtn);
        KurumsalRadioBtn.setText("Kurumsal");

        GirisYapBtn.setText("Giriş Yap");
        GirisYapBtn.addActionListener(this::GirisYapBtnActionPerformed);

        HesapOlusturBtn.setText("Hesap Oluştur");
        HesapOlusturBtn.addActionListener(this::HesapOlusturBtnActionPerformed);

        javax.swing.GroupLayout FirstPanelLayout = new javax.swing.GroupLayout(FirstPanel);
        FirstPanel.setLayout(FirstPanelLayout);
        FirstPanelLayout.setHorizontalGroup(
                FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                .addGap(376, 376, 376)
                                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                                .addComponent(BireyselRadioBtn)
                                                .addGap(63, 63, 63)
                                                .addComponent(KurumsalRadioBtn))
                                        .addComponent(GirisYapBtn)
                                        .addComponent(HesapOlusturBtn))
                                .addContainerGap(421, Short.MAX_VALUE))
        );
        FirstPanelLayout.setVerticalGroup(
                FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BireyselRadioBtn)
                                        .addComponent(KurumsalRadioBtn))
                                .addGap(48, 48, 48)
                                .addComponent(GirisYapBtn)
                                .addGap(47, 47, 47)
                                .addComponent(HesapOlusturBtn)
                                .addContainerGap(212, Short.MAX_VALUE))
        );

        PanelContainer.add(FirstPanel, "cardFirstPanel");

        BireyselGirisTamamlaBtn.setText("Giriş Yap");
        BireyselGirisTamamlaBtn.addActionListener(this::BireyselGirisTamamlaBtnActionPerformed);

        BireyselGirisTipiRDB.add(TCGirisRadioBtn);
        TCGirisRadioBtn.setText("TC İle Giriş");

        BireyselGirisTipiRDB.add(MusteriNoGirisRadioBtn);
        MusteriNoGirisRadioBtn.setText("Müşteri No İle Giriş");

        BireyselGirisTipiRDB.add(TelNoGirisRadioBtn);
        TelNoGirisRadioBtn.setText("Telefon No İle Giriş");

        BireyselTypeGirisTextF.setText("jTextField1");

        BireyselSifreGirisPasswordTF.setText("jPasswordField1");

        BireyselGirisSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout BireyselGirisYapPanelLayout = new javax.swing.GroupLayout(BireyselGirisYapPanel);
        BireyselGirisYapPanel.setLayout(BireyselGirisYapPanelLayout);
        BireyselGirisYapPanelLayout.setHorizontalGroup(
                BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addGroup(BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                                .addComponent(TCGirisRadioBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MusteriNoGirisRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TelNoGirisRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(BireyselTypeGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                                .addComponent(BireyselSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(BireyselGirisSifreGoster))
                                        .addComponent(BireyselGirisTamamlaBtn))
                                .addContainerGap(341, Short.MAX_VALUE))
        );
        BireyselGirisYapPanelLayout.setVerticalGroup(
                BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(TCGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                        .addComponent(MusteriNoGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TelNoGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addComponent(BireyselTypeGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BireyselSifreGirisPasswordTF)
                                        .addComponent(BireyselGirisSifreGoster))
                                .addGap(51, 51, 51)
                                .addComponent(BireyselGirisTamamlaBtn)
                                .addGap(167, 167, 167))
        );

        PanelContainer.add(BireyselGirisYapPanel, "cardBireyselGirisYapPanel");

        KurumsalGirisTamamlaBtn.setText("Giriş Yap");
        KurumsalGirisTamamlaBtn.addActionListener(this::KurumsalGirisTamamlaBtnActionPerformed);

        KurumKoduGirisTextF.setText("jTextField1");

        KurumsalSifreGirisPasswordTF.setText("jPasswordField2");

        KurumsalGirisSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout KurumsalGirisPanelLayout = new javax.swing.GroupLayout(KurumsalGirisPanel);
        KurumsalGirisPanel.setLayout(KurumsalGirisPanelLayout);
        KurumsalGirisPanelLayout.setHorizontalGroup(
                KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalGirisPanelLayout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addGroup(KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumKoduGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalGirisTamamlaBtn))
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalGirisSifreGoster)
                                .addContainerGap(381, Short.MAX_VALUE))
        );
        KurumsalGirisPanelLayout.setVerticalGroup(
                KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalGirisPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(KurumKoduGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(KurumsalSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalGirisSifreGoster))
                                .addGap(57, 57, 57)
                                .addComponent(KurumsalGirisTamamlaBtn)
                                .addContainerGap(236, Short.MAX_VALUE))
        );

        PanelContainer.add(KurumsalGirisPanel, "cardKurumsalGirisPanel");

        BireyselKayıtTamamlaBtn.setText("Kayıt Ol");
        BireyselKayıtTamamlaBtn.addActionListener(this::BireyselKayıtTamamlaBtnActionPerformed);

        BireyselAdGirisTextF.setText("jTextField1");

        BireyselSoyadGirisTextF.setText("jTextField1");

        try {
            BireyselTcGirisFormattedTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            BireyselDogumTGirisFormattedTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BireyselSehirGirisTextF.setText("jTextField1");

        try {
            BireyselTelefonGirisTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BireyselSifreKayitPasswordTF.setText("jPasswordField1");

        BireyselKayitSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout BireyselKayitPanelLayout = new javax.swing.GroupLayout(BireyselKayitPanel);
        BireyselKayitPanel.setLayout(BireyselKayitPanelLayout);
        BireyselKayitPanelLayout.setHorizontalGroup(
                BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BireyselKayitPanelLayout.createSequentialGroup()
                                .addContainerGap(415, Short.MAX_VALUE)
                                .addGroup(BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(BireyselAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSoyadGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselTcGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselDogumTGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselTelefonGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselKayıtTamamlaBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BireyselKayitSifreGoster)
                                .addGap(344, 344, 344))
        );
        BireyselKayitPanelLayout.setVerticalGroup(
                BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselKayitPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(BireyselAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(BireyselSoyadGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BireyselTcGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(BireyselDogumTGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BireyselSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(BireyselTelefonGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BireyselSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselKayitSifreGoster))
                                .addGap(18, 18, 18)
                                .addComponent(BireyselKayıtTamamlaBtn)
                                .addContainerGap(80, Short.MAX_VALUE))
        );

        PanelContainer.add(BireyselKayitPanel, "cardBireyselKayitPanel");

        KurumsalKayıtTamamlaBtn.setText("Kayıt Ol");
        KurumsalKayıtTamamlaBtn.addActionListener(this::KurumsalKayıtTamamlaBtnActionPerformed);

        KurumsalAdGirisTextF.setText("jTextField4");

        KurumsalTarihGirisFormattedTF.setText("jFormattedTextField5");

        KurumsalSehirGirisTextF.setText("jTextField5");

        KurumsalSifreKayitPasswordTF.setText("jPasswordField2");

        KurumsalKayitSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout KurumsalKayitPanelLayout = new javax.swing.GroupLayout(KurumsalKayitPanel);
        KurumsalKayitPanel.setLayout(KurumsalKayitPanelLayout);
        KurumsalKayitPanelLayout.setHorizontalGroup(
                KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KurumsalKayitPanelLayout.createSequentialGroup()
                                .addContainerGap(391, Short.MAX_VALUE)
                                .addGroup(KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumsalAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalTarihGirisFormattedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalKayıtTamamlaBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KurumsalKayitSifreGoster)
                                .addGap(379, 379, 379))
        );
        KurumsalKayitPanelLayout.setVerticalGroup(
                KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalKayitPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(KurumsalAdGirisTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalTarihGirisFormattedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalSehirGirisTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumsalKayitSifreGoster)
                                        .addComponent(KurumsalSifreKayitPasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalKayıtTamamlaBtn)
                                .addGap(113, 113, 113))
        );

        PanelContainer.add(KurumsalKayitPanel, "cardKurumsalKayitPanel");

        GeriDonBtn.setBackground(new java.awt.Color(0, 153, 102));
        GeriDonBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        GeriDonBtn.setText("<");
        GeriDonBtn.addActionListener(this::GeriDonBtnActionPerformed);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(GeriDonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GeriDonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>






    //===EVENTLER====
    private void GirisYapBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Eğer Bireysel seçiliyse -> Bireysel Giriş Ekranını ("kartBireysel") aç
        if (BireyselRadioBtn.isSelected()) {
            sayfaDegistir("cardBireyselGirisYapPanel");
        }

        // 2. Eğer Kurumsal seçiliyse -> Kurumsal Giriş Ekranını ("kartKurumsal") aç
        else if (KurumsalRadioBtn.isSelected()) {
            sayfaDegistir("cardKurumsalGirisPanel");
        }

        // 3. Hiçbiri seçili değilse kullanıcıyı uyar
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen giriş yapmak için bir hesap türü (Bireysel/Kurumsal) seçiniz!");
        }
    }

    private void HesapOlusturBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Eğer Bireysel seçiliyse -> Bireysel Kayıt Ekranına git
        if (BireyselRadioBtn.isSelected()) {
            // "kartBireyselKayit" ismini NetBeans'te vermiştik
            sayfaDegistir("cardBireyselKayitPanel");
        }

        // 2. Eğer Kurumsal seçiliyse -> Kurumsal Kayıt Ekranına git
        else if (KurumsalRadioBtn.isSelected()) {
            // "kartKurumsalKayit" ismini NetBeans'te vermiştik
            sayfaDegistir("cardKurumsalKayitPanel");
        }

        // 3. Hiçbiri seçili değilse uyar (Tedbir amaçlı)
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen önce hesap türünü (Bireysel/Kurumsal) seçiniz!");
        }
    }

    private void BireyselGirisTamamlaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Verileri Al
        String girilenVeri = BireyselTypeGirisTextF.getText();
        String girilenSifre = new String(BireyselSifreGirisPasswordTF.getPassword());

        // 2. Giriş Türünü Belirle
        String loginType = "";

        if (TCGirisRadioBtn.isSelected()) {
            loginType = "TC";
        } else if (MusteriNoGirisRadioBtn.isSelected()) {
            loginType = "MUSTERI_NO";
        } else if (TelNoGirisRadioBtn.isSelected()) {
            loginType = "TELEFON";
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen bir giriş yöntemi (TC/No/Tel) seçiniz.");
            return;
        }

        // 3. Veritabanına Sor (Yeni metoda 'loginType'ı da gönderiyoruz)
        model.IndividualUser bulunanKullanici = Managers.DataBaseManager.getIndividualUserByLogin(girilenVeri, girilenSifre, loginType);

        if (bulunanKullanici != null) {
            // BAŞARILI!
            BireyselKullaniciUI anaEkran = new BireyselKullaniciUI(bulunanKullanici);
            anaEkran.setVisible(true);
            this.dispose(); // Giriş ekranını kapat
        } else {
            // BAŞARISIZ
            javax.swing.JOptionPane.showMessageDialog(this, "Giriş Başarısız! Bilgilerinizi kontrol ediniz.");
        }
    }


    private void KurumsalGirisTamamlaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Verileri Al
        String kurumKodu = KurumKoduGirisTextF.getText();
        String sifre = new String(KurumsalSifreGirisPasswordTF.getPassword());

        // 2. Boşluk Kontrolü
        if(kurumKodu.isEmpty() || sifre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen Kurum Kodu ve Şifrenizi giriniz.");
            return;
        }

        // 3. Veritabanına Sor
        model.EnterpriseUser girisYapanSirket = Managers.DataBaseManager.getEnterpriseUserByLogin(kurumKodu, sifre);

        if (girisYapanSirket != null) {
            // BAŞARILI!
            KurumsalKullaniciUI sirketEkrani = new KurumsalKullaniciUI(girisYapanSirket);
            sirketEkrani.setVisible(true);

            javax.swing.JOptionPane.showMessageDialog(this, "Giriş Başarılı! (Şirket: " + girisYapanSirket.getEnterpriseName() + ")");
            this.dispose(); // Giriş ekranını kapat

        } else {
            // BAŞARISIZ
            javax.swing.JOptionPane.showMessageDialog(this, "Hatalı Kurum Kodu veya Şifre!");
        }
    }

    private void BireyselKayıtTamamlaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // 1. Formdaki Verileri Değişkenlere Alalım
            String ad = BireyselAdGirisTextF.getText();
            String soyad = BireyselSoyadGirisTextF.getText();
            String tc = BireyselTcGirisFormattedTextF.getText();     // Maskeli alandan gelir
            String sehir = BireyselSehirGirisTextF.getText();
            String tel = BireyselTelefonGirisTextF.getText();       // Maskeli alandan gelir
            String sifre = new String(BireyselSifreKayitPasswordTF.getPassword());

            // Tarih verisini String olarak alıyoruz (Örn: "01/01/1990")
            String tarihMetni = BireyselDogumTGirisFormattedTextF.getText();

            // 2. Boş Alan Kontrolü (Basit Validasyon)
            // Maskeli alanlar boşsa bazen sadece boşluk karakteri dönebilir, trim() ile temizleyelim.
            if (ad.trim().isEmpty() || soyad.trim().isEmpty() || sehir.trim().isEmpty() || sifre.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lütfen Ad, Soyad, Şehir ve Şifre alanlarını eksiksiz doldurunuz.");
                return;
            }

            // 3. Tarih Dönüştürme (String -> LocalDate)
            // Kullanıcı "Gün/Ay/Yıl" giriyor, Java'ya bunu öğretiyoruz.
            java.time.format.DateTimeFormatter formatlayici = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            java.time.LocalDate dogumTarihi = java.time.LocalDate.parse(tarihMetni, formatlayici);

            // 4. Veritabanı Yöneticisini Çağır ve Kaydet
            // DataBaseManager'da yazdığımız addIndividualUser metodunu kullanıyoruz.
            Managers.DataBaseManager.addIndividualUser(tc, ad, soyad, sifre, dogumTarihi, sehir, tel);

            // 5. Kullanıcıya Bilgi Ver
            javax.swing.JOptionPane.showMessageDialog(this, "Kayıt Başarılı! Giriş ekranına yönlendiriliyorsunuz.");

            // 6. Giriş Ekranına Geri Dön
            // Kullanıcı kaydolduktan sonra direkt giriş yapsın diye giriş paneline atıyoruz.
            sayfaDegistir("cardBireyselGirisYapPanel");

        } catch (java.time.format.DateTimeParseException ex) {
            // Eğer tarih formatı bozuksa (örn: 32/13/2020) burası çalışır
            javax.swing.JOptionPane.showMessageDialog(this, "Hatalı Tarih! Lütfen Gün/Ay/Yıl formatında giriniz.");
        } catch (Exception ex) {
            // Diğer hatalar için
            javax.swing.JOptionPane.showMessageDialog(this, "Bir hata oluştu: " + ex.getMessage());
        }
    }

    private void KurumsalKayıtTamamlaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // 1. Verileri Al
            String sirketAdi = KurumsalAdGirisTextF.getText();
            String sehirHQ = KurumsalSehirGirisTextF.getText();
            String sifre = new String(KurumsalSifreKayitPasswordTF.getPassword());
            String tarihMetni = KurumsalTarihGirisFormattedTF.getText();

            // 2. Kontrol
            if (sirketAdi.trim().isEmpty() || sehirHQ.trim().isEmpty() || sifre.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lütfen tüm alanları doldurunuz.");
                return;
            }

            // 3. Tarih
            java.time.format.DateTimeFormatter formatlayici = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            java.time.LocalDate kurulusTarihi = java.time.LocalDate.parse(tarihMetni, formatlayici);

            // 4. Kaydet ve KODU AL (String olusanKod)
            // Artık metodumuz bize String bir kod veriyor, onu yakalıyoruz:
            String olusanKod = Managers.DataBaseManager.addEnterpriseUser(sirketAdi, sifre, kurulusTarihi, sehirHQ);

            if (olusanKod != null) {
                // 5. Kodu Mesajda Göster
                String mesaj = "Kurumsal Kayıt Başarılı!\n\n" +
                        "GİRİŞ İÇİN KURUM KODUNUZ: " + olusanKod + "\n\n" +
                        "Lütfen bu kodu bir yere not ediniz.";

                javax.swing.JOptionPane.showMessageDialog(this, mesaj, "Kayıt Bilgisi", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // 6. Giriş Ekranına Yönlendir
                sayfaDegistir("cardKurumsalGirisPanel");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Kayıt sırasında bir hata oluştu!");
            }

        } catch (java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hatalı Tarih! Lütfen dd/MM/yyyy formatında giriniz.");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hata: " + ex.getMessage());
        }
    }

    private void GeriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Ana menüye (Seçim Ekranına) dön
        // Dün bu kartın ismini "cardFirstPanel" koymuştuk.
        sayfaDegistir("cardFirstPanel");
    }

    //======EVENTLER-SON=========

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuUI().setVisible(true));
    }

    //=======Kendi özel fonksiyonlarım=========
    private void sayfaDegistir(String kartIsmi) {
        // 1. Kartı Değiştir
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContainer.getLayout();
        layout.show(PanelContainer, kartIsmi);

        // 2. Buton Kontrolü Yap
        if (kartIsmi.equals("cardFirstPanel")) {
            // Eğer Ana Menüye dönüldüyse butonu GİZLE
            GeriDonBtn.setVisible(false);
        } else {
            // Diğer tüm sayfalarda butonu GÖSTER
            GeriDonBtn.setVisible(true);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton AdminControlsBtn;
    private javax.swing.ButtonGroup AnaMenuKullaniciTipiRDB;
    private javax.swing.JLabel BankaAdiLabel;
    private javax.swing.JTextField BireyselAdGirisTextF;
    private javax.swing.JFormattedTextField BireyselDogumTGirisFormattedTextF;
    private javax.swing.JCheckBox BireyselGirisSifreGoster;
    private javax.swing.JButton BireyselGirisTamamlaBtn;
    private javax.swing.ButtonGroup BireyselGirisTipiRDB;
    private javax.swing.JPanel BireyselGirisYapPanel;
    private javax.swing.JPanel BireyselKayitPanel;
    private javax.swing.JCheckBox BireyselKayitSifreGoster;
    private javax.swing.JButton BireyselKayıtTamamlaBtn;
    private javax.swing.JRadioButton BireyselRadioBtn;
    private javax.swing.JTextField BireyselSehirGirisTextF;
    private javax.swing.JPasswordField BireyselSifreGirisPasswordTF;
    private javax.swing.JPasswordField BireyselSifreKayitPasswordTF;
    private javax.swing.JTextField BireyselSoyadGirisTextF;
    private javax.swing.JFormattedTextField BireyselTcGirisFormattedTextF;
    private javax.swing.JFormattedTextField BireyselTelefonGirisTextF;
    private javax.swing.JTextField BireyselTypeGirisTextF;
    private javax.swing.JPanel FirstPanel;
    private javax.swing.JButton GeriDonBtn;
    private javax.swing.JButton GirisYapBtn;
    private javax.swing.JButton HesapOlusturBtn;
    private javax.swing.JTextField KurumKoduGirisTextF;
    private javax.swing.JTextField KurumsalAdGirisTextF;
    private javax.swing.JPanel KurumsalGirisPanel;
    private javax.swing.JCheckBox KurumsalGirisSifreGoster;
    private javax.swing.JButton KurumsalGirisTamamlaBtn;
    private javax.swing.JPanel KurumsalKayitPanel;
    private javax.swing.JCheckBox KurumsalKayitSifreGoster;
    private javax.swing.JButton KurumsalKayıtTamamlaBtn;
    private javax.swing.JRadioButton KurumsalRadioBtn;
    private javax.swing.JTextField KurumsalSehirGirisTextF;
    private javax.swing.JPasswordField KurumsalSifreGirisPasswordTF;
    private javax.swing.JPasswordField KurumsalSifreKayitPasswordTF;
    private javax.swing.JFormattedTextField KurumsalTarihGirisFormattedTF;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MusteriNoGirisRadioBtn;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JRadioButton TCGirisRadioBtn;
    private javax.swing.JLabel TarihveSaatLabel;
    private javax.swing.JRadioButton TelNoGirisRadioBtn;
    private javax.swing.JPanel UstPanel;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration
}
