import java.awt.CardLayout;

/**
 * @author akifa
 */
public class MainMenuUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuUI.class.getName());

    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI() {
        initComponents();
        GeriDonBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        AnaMenuKullaniciTipiRDB = new javax.swing.ButtonGroup();
        BireyselGirisTipiRDB = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        MainPanel = new javax.swing.JPanel();
        PanelContainer = new javax.swing.JPanel();
        FirstPanel = new javax.swing.JPanel();
        BireyselRadioBtn = new javax.swing.JRadioButton();
        KurumsalRadioBtn = new javax.swing.JRadioButton();
        GirisYapBtn = new javax.swing.JButton();
        HesapOlusturBtn = new javax.swing.JButton();
        BireyselGirisYapPanel = new javax.swing.JPanel();
        TCGirisRadioBtn = new javax.swing.JRadioButton();
        MusteriNoGirisRadioBtn = new javax.swing.JRadioButton();
        TelNoGirisRadioBtn = new javax.swing.JRadioButton();
        BireyselTypeGirisTextF = new javax.swing.JTextField();
        BireyselSifreGirisPasswordTF = new javax.swing.JPasswordField();
        KurumsalGirisPanel = new javax.swing.JPanel();
        KurumKoduGirisTextF = new javax.swing.JTextField();
        KurumsalSifreGirisPasswordTF = new javax.swing.JPasswordField();
        KurumsalKayitPanel = new javax.swing.JPanel();
        KurumsalAdGirisTextF = new javax.swing.JTextField();
        KurumsalTarihGirisFormattedTF = new javax.swing.JFormattedTextField();
        KurumsalSehirGirisTextF = new javax.swing.JTextField();
        KurumsalSifreKayitPasswordTF = new javax.swing.JPasswordField();
        KurumsalKayitSifreGoster = new javax.swing.JCheckBox();
        BireyselKayitPanel = new javax.swing.JPanel();
        BireyselAdGirisTextF = new javax.swing.JTextField();
        BireyselSoyadGirisTextF = new javax.swing.JTextField();
        BireyselTcGirisFormattedTextF = new javax.swing.JFormattedTextField();
        BireyselDogumTGirisFormattedTextF = new javax.swing.JFormattedTextField();
        BireyselSehirGirisTextF = new javax.swing.JTextField();
        BireyselTelefonGirisTextF = new javax.swing.JFormattedTextField();
        BireyselSifreKayitPasswordTF = new javax.swing.JPasswordField();
        BireyselKayitSifreGoster = new javax.swing.JCheckBox();
        BankaAdiLabel = new javax.swing.JLabel();
        AdminControlsBtn = new javax.swing.JButton();
        TarihveSaatLabel = new javax.swing.JLabel();
        GeriDonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContainer.setMinimumSize(new java.awt.Dimension(600, 350));
        PanelContainer.setPreferredSize(new java.awt.Dimension(600, 350));
        PanelContainer.setLayout(new java.awt.CardLayout());

        AnaMenuKullaniciTipiRDB.add(BireyselRadioBtn);
        BireyselRadioBtn.setText("Bireysel");

        AnaMenuKullaniciTipiRDB.add(KurumsalRadioBtn);
        KurumsalRadioBtn.setText("Kurumsal");

        GirisYapBtn.setText("Giriş Yap");
        GirisYapBtn.addActionListener(this::GirisYapBtnActionPerformed);

        HesapOlusturBtn.setText("Hesap Oluştur");
        HesapOlusturBtn.addActionListener(this::HesapOlusturBtnActionPerformed);

        javax.swing.GroupLayout FirstPanelLayout = new javax.swing.GroupLayout(FirstPanel);
        FirstPanel.setLayout(FirstPanelLayout);
        FirstPanelLayout.setHorizontalGroup(
                FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                                .addComponent(BireyselRadioBtn)
                                                .addGap(63, 63, 63)
                                                .addComponent(KurumsalRadioBtn))
                                        .addComponent(GirisYapBtn)
                                        .addComponent(HesapOlusturBtn))
                                .addContainerGap(199, Short.MAX_VALUE))
        );
        FirstPanelLayout.setVerticalGroup(
                FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FirstPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BireyselRadioBtn)
                                        .addComponent(KurumsalRadioBtn))
                                .addGap(48, 48, 48)
                                .addComponent(GirisYapBtn)
                                .addGap(47, 47, 47)
                                .addComponent(HesapOlusturBtn)
                                .addContainerGap(118, Short.MAX_VALUE))
        );

        PanelContainer.add(FirstPanel, "cardFirstPanel");

        BireyselGirisTipiRDB.add(TCGirisRadioBtn);
        TCGirisRadioBtn.setText("TC İle Giriş");

        BireyselGirisTipiRDB.add(MusteriNoGirisRadioBtn);
        MusteriNoGirisRadioBtn.setText("Müşteri No İle Giriş");

        BireyselGirisTipiRDB.add(TelNoGirisRadioBtn);
        TelNoGirisRadioBtn.setText("Telefon No İle Giriş");

        BireyselTypeGirisTextF.setText("jTextField1");

        BireyselSifreGirisPasswordTF.setText("jPasswordField1");

        javax.swing.GroupLayout BireyselGirisYapPanelLayout = new javax.swing.GroupLayout(BireyselGirisYapPanel);
        BireyselGirisYapPanel.setLayout(BireyselGirisYapPanelLayout);
        BireyselGirisYapPanelLayout.setHorizontalGroup(
                BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                                .addComponent(TCGirisRadioBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MusteriNoGirisRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TelNoGirisRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(BireyselTypeGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(208, 208, 208))
        );
        BireyselGirisYapPanelLayout.setVerticalGroup(
                BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselGirisYapPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(BireyselGirisYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(TCGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MusteriNoGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TelNoGirisRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addComponent(BireyselTypeGirisTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(BireyselSifreGirisPasswordTF)
                                .addGap(125, 125, 125))
        );

        PanelContainer.add(BireyselGirisYapPanel, "cardBireyselGirisYapPanel");

        KurumKoduGirisTextF.setText("jTextField1");

        KurumsalSifreGirisPasswordTF.setText("jPasswordField2");

        javax.swing.GroupLayout KurumsalGirisPanelLayout = new javax.swing.GroupLayout(KurumsalGirisPanel);
        KurumsalGirisPanel.setLayout(KurumsalGirisPanelLayout);
        KurumsalGirisPanelLayout.setHorizontalGroup(
                KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalGirisPanelLayout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addGroup(KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumKoduGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(264, Short.MAX_VALUE))
        );
        KurumsalGirisPanelLayout.setVerticalGroup(
                KurumsalGirisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalGirisPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(KurumKoduGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(KurumsalSifreGirisPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(208, Short.MAX_VALUE))
        );

        PanelContainer.add(KurumsalGirisPanel, "cardKurumsalGirisPanel");

        KurumsalAdGirisTextF.setText("jTextField4");

        KurumsalTarihGirisFormattedTF.setText("jFormattedTextField5");

        KurumsalSehirGirisTextF.setText("jTextField5");

        KurumsalSifreKayitPasswordTF.setText("jPasswordField2");

        KurumsalKayitSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout KurumsalKayitPanelLayout = new javax.swing.GroupLayout(KurumsalKayitPanel);
        KurumsalKayitPanel.setLayout(KurumsalKayitPanelLayout);
        KurumsalKayitPanelLayout.setHorizontalGroup(
                KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalKayitPanelLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addGroup(KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumsalAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalTarihGirisFormattedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KurumsalSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KurumsalKayitSifreGoster)
                                .addGap(166, 166, 166))
        );
        KurumsalKayitPanelLayout.setVerticalGroup(
                KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KurumsalKayitPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(KurumsalAdGirisTextF)
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalTarihGirisFormattedTF)
                                .addGap(18, 18, 18)
                                .addComponent(KurumsalSehirGirisTextF)
                                .addGap(18, 18, 18)
                                .addGroup(KurumsalKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(KurumsalKayitSifreGoster)
                                        .addComponent(KurumsalSifreKayitPasswordTF))
                                .addGap(158, 158, 158))
        );

        PanelContainer.add(KurumsalKayitPanel, "cardKurumsalKayitPanel");

        BireyselAdGirisTextF.setText("jTextField1");

        BireyselSoyadGirisTextF.setText("jTextField1");

        try {
            BireyselTcGirisFormattedTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            BireyselDogumTGirisFormattedTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BireyselSehirGirisTextF.setText("jTextField1");

        try {
            BireyselTelefonGirisTextF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BireyselSifreKayitPasswordTF.setText("jPasswordField1");

        BireyselKayitSifreGoster.setText("Şifreyi Göster");

        javax.swing.GroupLayout BireyselKayitPanelLayout = new javax.swing.GroupLayout(BireyselKayitPanel);
        BireyselKayitPanel.setLayout(BireyselKayitPanelLayout);
        BireyselKayitPanelLayout.setHorizontalGroup(
                BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselKayitPanelLayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addGroup(BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(BireyselAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSoyadGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselTcGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselDogumTGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselTelefonGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BireyselKayitSifreGoster)
                                .addGap(133, 133, 133))
        );
        BireyselKayitPanelLayout.setVerticalGroup(
                BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BireyselKayitPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(BireyselAdGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(BireyselSoyadGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BireyselTcGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(BireyselDogumTGirisFormattedTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BireyselSehirGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(BireyselTelefonGirisTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BireyselKayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BireyselSifreKayitPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BireyselKayitSifreGoster))
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        PanelContainer.add(BireyselKayitPanel, "cardBireyselKayitPanel");

        BankaAdiLabel.setText("DİNO BANK");

        AdminControlsBtn.setText("AdminControls");

        TarihveSaatLabel.setText("Tarih ve Saat");

        GeriDonBtn.setText("<");
        GeriDonBtn.addActionListener(this::GeriDonBtnActionPerformed);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(TarihveSaatLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BankaAdiLabel)
                                .addGap(312, 312, 312)
                                .addComponent(AdminControlsBtn)
                                .addGap(41, 41, 41))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addGap(200, 200, 200)
                                                .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(GeriDonBtn)))
                                .addContainerGap(200, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addComponent(TarihveSaatLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(GeriDonBtn)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(AdminControlsBtn)
                                                        .addComponent(BankaAdiLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                                .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>






    //===EVENTLER====
    private void GirisYapBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Eğer Bireysel seçiliyse -> Bireysel Giriş Ekranını ("kartBireysel") aç
        if (BireyselRadioBtn.isSelected()) {
            sayfaDegistir("cardBireyselGirisYapPanel");
        }

        // 2. Eğer Kurumsal seçiliyse -> Kurumsal Giriş Ekranını ("kartKurumsal") aç
        else if (KurumsalRadioBtn.isSelected()) {
            sayfaDegistir("cardKurumsalGirisPanel");
        }

        // 3. Hiçbiri seçili değilse kullanıcıyı uyar
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen giriş yapmak için bir hesap türü (Bireysel/Kurumsal) seçiniz!");
        }
    }

    private void HesapOlusturBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Eğer Bireysel seçiliyse -> Bireysel Kayıt Ekranına git
        if (BireyselRadioBtn.isSelected()) {
            // "kartBireyselKayit" ismini NetBeans'te vermiştik
            sayfaDegistir("cardBireyselKayitPanel");
        }

        // 2. Eğer Kurumsal seçiliyse -> Kurumsal Kayıt Ekranına git
        else if (KurumsalRadioBtn.isSelected()) {
            // "kartKurumsalKayit" ismini NetBeans'te vermiştik
            sayfaDegistir("cardKurumsalKayitPanel");
        }

        // 3. Hiçbiri seçili değilse uyar (Tedbir amaçlı)
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen önce hesap türünü (Bireysel/Kurumsal) seçiniz!");
        }
    }

    private void GeriDonBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Ana menüye (Seçim Ekranına) dön
        // Dün bu kartın ismini "cardFirstPanel" koymuştuk.
        sayfaDegistir("cardFirstPanel");
        //GeriDonBtn.setVisible(false);
    }

    //======EVENTLER-SON=========

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuUI().setVisible(true));
    }

    //=======Kendi özel fonksiyonlarım=========
    private void sayfaDegistir(String kartIsmi) {
        // 1. Kartı Değiştir
        java.awt.CardLayout layout = (java.awt.CardLayout) PanelContainer.getLayout();
        layout.show(PanelContainer, kartIsmi);

        // 2. Buton Kontrolü Yap
        if (kartIsmi.equals("cardFirstPanel")) {
            // Eğer Ana Menüye dönüldüyse butonu GİZLE
            GeriDonBtn.setVisible(false);
        } else {
            // Diğer tüm sayfalarda butonu GÖSTER
            GeriDonBtn.setVisible(true);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton AdminControlsBtn;
    private javax.swing.ButtonGroup AnaMenuKullaniciTipiRDB;
    private javax.swing.JLabel BankaAdiLabel;
    private javax.swing.JTextField BireyselAdGirisTextF;
    private javax.swing.JFormattedTextField BireyselDogumTGirisFormattedTextF;
    private javax.swing.ButtonGroup BireyselGirisTipiRDB;
    private javax.swing.JPanel BireyselGirisYapPanel;
    private javax.swing.JPanel BireyselKayitPanel;
    private javax.swing.JCheckBox BireyselKayitSifreGoster;
    private javax.swing.JRadioButton BireyselRadioBtn;
    private javax.swing.JTextField BireyselSehirGirisTextF;
    private javax.swing.JPasswordField BireyselSifreGirisPasswordTF;
    private javax.swing.JPasswordField BireyselSifreKayitPasswordTF;
    private javax.swing.JTextField BireyselSoyadGirisTextF;
    private javax.swing.JFormattedTextField BireyselTcGirisFormattedTextF;
    private javax.swing.JFormattedTextField BireyselTelefonGirisTextF;
    private javax.swing.JTextField BireyselTypeGirisTextF;
    private javax.swing.JPanel FirstPanel;
    private javax.swing.JButton GeriDonBtn;
    private javax.swing.JButton GirisYapBtn;
    private javax.swing.JButton HesapOlusturBtn;
    private javax.swing.JTextField KurumKoduGirisTextF;
    private javax.swing.JTextField KurumsalAdGirisTextF;
    private javax.swing.JPanel KurumsalGirisPanel;
    private javax.swing.JPanel KurumsalKayitPanel;
    private javax.swing.JCheckBox KurumsalKayitSifreGoster;
    private javax.swing.JRadioButton KurumsalRadioBtn;
    private javax.swing.JTextField KurumsalSehirGirisTextF;
    private javax.swing.JPasswordField KurumsalSifreGirisPasswordTF;
    private javax.swing.JPasswordField KurumsalSifreKayitPasswordTF;
    private javax.swing.JFormattedTextField KurumsalTarihGirisFormattedTF;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MusteriNoGirisRadioBtn;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JRadioButton TCGirisRadioBtn;
    private javax.swing.JLabel TarihveSaatLabel;
    private javax.swing.JRadioButton TelNoGirisRadioBtn;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration
}
